-- +goose Up

-- +goose StatementBegin
-- All badge related metadata is to be found here.
INSERT INTO badge_info (id, name, description) VALUES
('b7e1a3b0-f1a0-4b3c-8e1d-9a2b3c4e5f6a', 'Hello, Tinkerer', '1 Pull Requests merged'),
('c8f2b4c1-0a1b-4d2e-9f3a-5b4c6d7e8f9b', 'Ninja Contributor', '5 Pull Requests merged'),
('d9g3c5d2-1b2c-4e3f-af4b-6c5d7e8f0a1c', 'Engineer Overclocked', '10 Pull Requests merged'),
('e0h4d6e3-2c3d-4f4g-bf5c-7d6e8f9a2b3d', 'Doomguy', '20 Pull Requests merged'),
('f1i5e7f4-3d4e-4g5h-cf6d-8e7f9a0b4c5e', 'Sanitizer', 'Get 1 bug reports accepted'),
('a2j6f8g5-4e5f-5h6i-df7e-9f0a1b2c3d4f', 'Pest Control', 'Get 5 bug reports accepted'),
('b3k7g9h6-5f6g-6i7j-ef8f-0a1b2c3d4e5g', 'Planet Cleanser', 'Get 10 bug reports accepted'),
('c4l8h0i7-6g7h-7j8k-ff9a-1b2c3d4e5f6h', 'Polygot', 'Contribute in 3 different languages'),
('d5m9i1j8-7h8i-8k9l-ag0b-2c3d4e5f6g7i', 'Jack of All Stacks', 'Contribute in 5 different languages'),
('e6n0j2k9-8i9j-9l0m-bh1c-3d4e5f6g7h8j', 'The Scholar', 'Help out 1 person in SoC comms'),
('f7o1k3l0-9j0k-0m1n-ci2d-4e5f6g7h8i9k', 'The Gulliver', 'Help out 3 people in SoC comms'),
('a8p2l4m1-0k1l-1n2o-dj3e-5f6g7h8i9j0l', 'The Oracle', 'Help out 5 people in SoC comms'),
('b9q3m5n2-1l2m-2o3p-ek4f-6g7h8i9j0k1m', 'Lab Assistant', 'Get 1 testing related Pull Requests merged'),
('c0r4n6o3-2m3n-3p4q-fl5g-7h8i9j0k1l2n', 'Quality Assurer', 'Get 5 testing related Pull Requests merged'),
('d1s5o7p4-3n4o-4q5r-gm6h-8i9j0k1l2m3o', 'Full-Coded Alchemist', 'Get 10 testing related Requests merged'),
('e2t6p8q5-4o5p-5r6s-hn7i-9j0k1l2m3n4p', 'High Charity', 'Get 2 feature suggestions accepted'),
('f3u7q9r6-5p6q-6s7t-io8j-0k1l2m3n4o5q', 'Zeppelin of Mighty Gargantuaness (ZOMG)', 'Get a PR marked for High-Impact'),
('a4v8r0s7-6q7r-7t8u-jp9k-1l2m3n4o5p6r', 'Doc Champ', 'Get 2 documentation Pull Requests merged'),
('b5w9s1t8-7r8s-8u9v-kq0l-2m3n4o5p6q7s', 'Shaman', 'Reach 250 bounty points'),
('c6x0t2u9-8s9t-9v0w-lr1m-3n4o5p6q7r8t', 'Henchman', 'Reach 500 bounty points'),
('d7y1u3v0-9t0u-0w1x-ms2n-4o5p6q7r8s9u', 'Kingpin', 'Reach 750 bounty points'),
('e8z2v4w1-0u1v-1x2y-nt3o-5p6q7r8s9t0v', 'The Godfather', 'Reach 1000 bounty points'),
('f9a3w5x2-1v2w-2y3z-ou4p-6q7r8s9t0u1w', '2 Pincers and Maximum Effort', 'Most Rust issues solved (1st place)'),
('a0b4x6y3-2w3x-3z4a-pv5q-7r8s9t0u1v2x', 'Crabby Coder', 'Most Rust issues solved (2nd place)'),
('b1c5y7z4-3x4y-4a5b-qw6r-8s9t0u1v2w3y', 'Salamander Spirit', 'Most Zig issues solved (1st place)'),
('c2d6z8a5-4y5z-5b6c-rx7s-9t0u1v2w3x4z', 'Salamander Totem', 'Most Zig issues solved (2nd place)'),
('d3e7a9b6-5z6a-6c7d-sy8t-0u1v2w3x4y5a', 'Mamba Mentality', 'Most Python issues solved (1st place)'),
('e4f8b0c7-6a7b-7d8e-tz9u-1v2w3x4y5z6b', 'Basilisk Defanged', 'Most Python issues solved (2nd place)'),
('f5g9c1d8-7b8c-8e9f-ua0v-2w3x4y5z6a7c', 'Apex Gopher', 'Most Go issues solved (1st place)'),
('a6h0d2e9-8c9d-9f0g-vb1w-3x4y5z6a7b8d', 'Primal Gopher', 'Most Go issues solved (2nd place)'),
('b7i1e3f0-9d0e-0g1h-wc2x-4y5z6a7b8c9e', 'Forge Smelter', 'Most JS/TS issues solved (1st place)'),
('c8j2f4g1-0e1f-1h2i-xd3y-5z6a7b8c9d0f', 'Prop Driller', 'Most JS/TS issues solved (2nd place)'),
('d9k3g5h2-1f2g-2i3j-ye4z-6a7b8c9d0e1g', 'Lore Master', 'Make a submission accepted for each weekly challenge'),
('e0l4h6i3-2g3h-3j4k-zf5a-7b8c9d0e1f2h', 'Pirate of Issue-bians', 'Contribute to 10 issues in the same language'),
('f1m5i7j4-3h4i-4k5l-ag6b-8c9d0e1f2g3i', 'Enamoured', 'Got a PR accepted every week for a month');
-- +goose StatementEnd

-- +goose StatementBegin
-- Seed data for maintainers for Season of Code 2025 (S2)
INSERT INTO maintainers (ghUsername, full_name) VALUES
('Ashrockzzz2003', 'Ashwin Narayanan S'),
('karthik-saiharsh', 'Karthik Saiharsh'),
('ShyamSundhar1411', 'Shyam Sundhar'),
('Astrasv', 'Sudharsan Vanamali'),
('akshayxml', 'Akshay M');
-- +goose StatementEnd

-- +goose StatementBegin
-- Seed data for internal and external repos for Season of Code 2025 (S2)
INSERT INTO repository
  (id, name, description, url, maintainers, tags, is_internal) VALUES
(
  gen_random_uuid(),
  'Placement Tracker Web App',
  'Web App for tracking the placement activities of the students of Amrita School of Computing, Coimbatore.',
  'https://github.com/Ashrockzzz2003/placement_tracker_web',
  '{"Ashrockzzz2003"}',
  '{"nextjs", "javascript", "tailwindcss", "chartjs"}',
  true),
(
  gen_random_uuid(),
  'Placement Tracker Server',
  'Backend for the web app for tracking placement activities.',
  'https://github.com/Ashrockzzz2003/placement_tracker_server',
  '{"Ashrockzzz2003"}',
  '{"javascript", "expressjs", "mysql"}',
  true),
(
  gen_random_uuid(),
  'EvOC runner_controller_microservice',
  'Microservice for controlling the execution of Evolutionary Algorithms.',
  'https://github.com/Evolutionary-Algorithms-On-Click/runner_controller_microservice',
  '{"Ashrockzzz2003"}',
  '{"docker", "go", "http", "protobuf", "cookie", "grpc"}',
  true),
(
  gen_random_uuid(),
  'EvOC runner',
  'Component responsible for running the Evolutionary Algorithms.', 
  'https://github.com/Evolutionary-Algorithms-On-Click/runner', 
  '{"Ashrockzzz2003"}', 
  '{"python", "docker", "rabbitmq", "cockroachdb"}',
  true),
(
  gen_random_uuid(),
  'EvOC operations', 
  'Repository for operational aspects and automation.', 
  'https://github.com/Evolutionary-Algorithms-On-Click/operations', 
  '{"Ashrockzzz2003"}', 
  '{"docker", "ansible"}',
  true),
(
  gen_random_uuid(),
  'EvOC user_docs', 
  'Documentation for users of the Evolutionary Algorithms platform.', 
  'https://github.com/Evolutionary-Algorithms-On-Click/user_docs', 
  '{"Ashrockzzz2003"}', 
  '{"markdown", "docs", "vitepress"}',
  true),
(
  gen_random_uuid(),
  'EvOC dev_docs', 
  'Documentation for developers contributing to the Evolutionary Algorithms platform.', 
  'https://github.com/Evolutionary-Algorithms-On-Click/dev_docs', 
  '{"Ashrockzzz2003"}', 
  '{"markdown", "docs", "vitepress"}', 
  true),
(
  gen_random_uuid(),
  'EvOC frontend', 
  'Frontend for the Evolutionary Algorithms platform.', 
  'https://github.com/Evolutionary-Algorithms-On-Click/evolve_frontend', 
  '{"Ashrockzzz2003"}', 
  '{"nextjs", "cookies", "gemini", "tailwindcss", "vercel"}',
  true),
(
  gen_random_uuid(),
  'EvOC auth_microservice', 
  'Microservice for handling authentication for the platform.', 
  'https://github.com/Evolutionary-Algorithms-On-Click/auth_microservice', 
  '{"Ashrockzzz2003"}', 
  '{"docker", "go", "http", "protobuf", "cookie", "grpc"}',
  true),
(
  gen_random_uuid(),
  'Quick Start Express', 
  'A simple CLI tool to generate Express servers from multiple available templates.', 
  'https://github.com/CSE-25/quick_start_express', 
  '{"Ashrockzzz2003"}', 
  '{"javascript", "cli", "vitepress", "markdown"}',
  true),
(
  gen_random_uuid(),
  'Amrita PYQ', 
  'The Amrita PYQ CLI Tool simplifies accessing previous year question papers.', 
  'https://github.com/CSE-25/amrita_pyq', 
  '{"Ashrockzzz2003"}', 
  '{"go", "cli"}',
  true),
(
  gen_random_uuid(),
  'SLTS 2025', 
  'Firebase powered app to view and analyze registrations and judge participants for SLTS-2025.', 
  'https://github.com/Ashrockzzz2003/slts-2024', 
  '{"Ashrockzzz2003"}', 
  '{"firebase", "nextjs", "tailwindcss", "javascript", "python"}',
  true),
(
  gen_random_uuid(),
  'Vault 007 v2.0', 
  'Flutter Mobile app to manage and remember passwords.', 
  'https://github.com/Ashrockzzz2003/Vault_007', 
  '{"Ashrockzzz2003"}', 
  '{"flutter", "dart", "material"}',
  true),
(
  gen_random_uuid(),
  'ANSAN v4.0', 
  'Mobile app to detect glaucoma early, powered by Firebase.', 
  'https://github.com/Ashrockzzz2003/ansan_v3', 
  '{"Ashrockzzz2003"}', 
  '{"flutter", "firebase", "dart"}',
  true),
(
  gen_random_uuid(),
  'Anokha 2025 Event Proposals Management App',
  'A platform for submitting, reviewing, and managing event proposals for Anokha 2025.',
  'https://github.com/SudharsanSaravanan/event-proposal-app', 
  '{"Ashrockzzz2003"}',
  '{"firebase", "nextjs", "javascript", tailwindcss"}',
  true),
(
  gen_random_uuid(),
  'File-Sharing-App',
  'A web application for sharing files.', 
  'https://github.com/karthik-saiharsh/file-sharing-app',
  '{"karthik-saiharsh"}',
  '{"nextjs", "typescript"}',
  true),
(
  gen_random_uuid(), 
  'PANAM (Money Management related App)', 
  'Supercharge your investment tracking with this secure, Google Sheets-powered portfolio manager. Visualize growth, analyze performance, and take control of your financial future—all within your private Google ecosystem.', 
  'https://github.com/akshayxml/panam', 
  '{"Ashrockzzz2003", "akshayxml"}', 
  '{"google-sheets", "typescript", "google-appscript"}', 
  false),
(
  gen_random_uuid(), 
  'Git-automater', 
  'A Rust-powered CLI tool that simplifies Git workflows by automating common version control tasks.', 
  'https://github.com/ShyamSundhar1411/git-automater', 
  '{"ShyamSundhar1411"}', 
  '{"rust", "cli"}', 
  false),
(
  gen_random_uuid(), 
  'Structura-py', 
  'Structura is a CLI tool that automates folder structure generation and dependency management for Python projects.', 
  'https://github.com/ShyamSundhar1411/structura-py', 
  '{"ShyamSundhar1411"}', 
  '{"python", "cli"}', 
  false),
(
  gen_random_uuid(), 
  'Structura-Go', 
  'Structura is a CLI tool for automated folder structure generation and dependency management in Golang projects.',
  'https://github.com/ShyamSundhar1411/structura-go',
  '{"ShyamSundhar1411"}',
  '{"go", "cli"}',
  false);
-- +goose StatementEnd
