-- +goose Up

-- +goose StatementBegin
-- All badge related metadata is to be found here.
INSERT INTO badge_info (name, description) VALUES
('Hello, Tinkerer', '1 Pull Requests merged'),
('Ninja Contributor', '5 Pull Requests merged'),
('Engineer Overclocked', '10 Pull Requests merged'),
('Doomguy', '20 Pull Requests merged'),
('Sanitizer', 'Get 1 bug reports accepted'),
('Pest Control', 'Get 5 bug reports accepted'),
('Planet Cleanser', 'Get 10 bug reports accepted'),
('Polygot', 'Contribute in 3 different languages'),
('Jack of All Stacks', 'Contribute in 5 different languages'),
('The Scholar', 'Help out 1 person in SoC comms'),
('The Gulliver', 'Help out 3 people in SoC comms'),
('The Oracle', 'Help out 5 people in SoC comms'),
('Lab Assistant', 'Get 1 testing related Pull Requests merged'),
('Quality Assurer', 'Get 5 testing related Pull Requests merged'),
('Full-Coded Alchemist', 'Get 10 testing related Requests merged'),
('High Charity', 'Get 2 feature suggestions accepted'),
('Zeppelin of Mighty Gargantuaness (ZOMG)', 'Get a PR marked for High-Impact'),
('Doc Champ', 'Get 2 documentation Pull Requests merged'),
('Pirate of Issue-bians', 'Contribute to 10 issues in the same language'),
('Enamoured', 'Got a PR accepted every week for a month');
-- +goose StatementEnd

-- +goose StatementBegin
-- Seed data for maintainers for Season of Code 2025 (S2)
INSERT INTO maintainers (ghUsername, full_name) VALUES
-- Internals
('Ashrockzzz2003', 'Ashwin Narayanan S'),
('aadit-n3rdy', 'E Aadithyaa'),
('Astrasv', 'Sudharsan Vanamali'),
('Leela0o5', 'Leela M'),
('adithya-menon-r', 'Adithya Menon R'),
('BIJJUDAMA', 'Nitansh Shankar'),
('karthik-saiharsh', 'Karthik Saiharsh'),
('Thanus-Kumaar', 'Thanus Kumaar'),
('TharunKumarrA', 'Tharun Kumarr'),
('ritwik-m', 'Ritwik M'),
('ariyha', 'Nithish Ariyha'),
('Naganathan05', 'Naganathan M'),
('Nithin0306', 'Nithin Venkat Sharma PM'),
-- Externals
('ShyamSundhar1411', 'Shyam Sundhar'),
('akshayxml', 'Akshay M'),
('nasacode1', 'Maanasa Ganesh'),
('aniket2909', 'Aniket Sharma'),
('SakethRamanKS', 'Saketh Raman');
-- +goose StatementEnd

-- +goose StatementBegin
-- Seed data for internal and external repos for Season of Code 2025 (S2)
INSERT INTO repository
  (id, name, description, url, maintainers, tags, is_internal) VALUES
(
  gen_random_uuid(),
  'Placement Tracker Web App',
  'Web App for tracking the placement activities of the students of Amrita School of Computing, Coimbatore.',
  'https://github.com/Ashrockzzz2003/placement_tracker_web',
  '{"Ashrockzzz2003"}',
  '{"Next", "JavaScript", "TailwindCSS", "Chartjs"}',
  true),
(
  gen_random_uuid(),
  'Placement Tracker Server',
  'Backend for the web app for tracking placement activities.',
  'https://github.com/Ashrockzzz2003/placement_tracker_server',
  '{"Ashrockzzz2003"}',
  '{"JavaScript", "Express", "MySQL"}',
  true),
(
  gen_random_uuid(),
  'EvOC runner_controller_microservice',
  'Microservice for controlling the execution of Evolutionary Algorithms.',
  'https://github.com/Evolutionary-Algorithms-On-Click/runner_controller_microservice',
  '{"Ashrockzzz2003"}',
  '{"Docker", "Go", "gRPC", "Cookies"}',
  true),
(
  gen_random_uuid(),
  'EvOC runner',
  'Component responsible for running the Evolutionary Algorithms.', 
  'https://github.com/Evolutionary-Algorithms-On-Click/runner', 
  '{"Ashrockzzz2003"}', 
  '{"Python", "Docker", "RabbitMQ", "CockroachDB"}',
  true),
(
  gen_random_uuid(),
  'EvOC operations', 
  'Repository for operational aspects and automation.', 
  'https://github.com/Evolutionary-Algorithms-On-Click/operations', 
  '{"Ashrockzzz2003"}', 
  '{"Docker", "Ansible"}',
  true),
(
  gen_random_uuid(),
  'EvOC user_docs', 
  'Documentation for users of the Evolutionary Algorithms platform.', 
  'https://github.com/Evolutionary-Algorithms-On-Click/user_docs', 
  '{"Ashrockzzz2003"}', 
  '{"Markdown", "Vitepress"}',
  true),
(
  gen_random_uuid(),
  'EvOC dev_docs', 
  'Documentation for developers contributing to the Evolutionary Algorithms platform.', 
  'https://github.com/Evolutionary-Algorithms-On-Click/dev_docs', 
  '{"Ashrockzzz2003"}', 
  '{"Markdown", "Vitepress"}', 
  true),
(
  gen_random_uuid(),
  'EvOC frontend', 
  'Frontend for the Evolutionary Algorithms platform.', 
  'https://github.com/Evolutionary-Algorithms-On-Click/evolve_frontend', 
  '{"Ashrockzzz2003"}', 
  '{"Next", "Gemini", "TailwindCSS", "Vercel"}',
  true),
(
  gen_random_uuid(),
  'EvOC auth_microservice', 
  'Microservice for handling authentication for the platform.', 
  'https://github.com/Evolutionary-Algorithms-On-Click/auth_microservice', 
  '{"Ashrockzzz2003"}', 
  '{"Docker", "Go", "gRPC", "Cookies"}',
  true),
(
  gen_random_uuid(),
  'Quick Start Express', 
  'A simple CLI tool to generate Express servers from multiple available templates.', 
  'https://github.com/CSE-25/quick_start_express', 
  '{"Ashrockzzz2003"}', 
  '{"JavaScript", "Vitepress", "Markdown"}',
  true),
(
  gen_random_uuid(),
  'Amrita PYQ', 
  'The Amrita PYQ CLI Tool simplifies accessing previous year question papers.', 
  'https://github.com/CSE-25/amrita_pyq', 
  '{"Ashrockzzz2003"}', 
  '{"Go", "Cobra"}',
  true),
(
  gen_random_uuid(),
  'SLTS 2025', 
  'Firebase powered app to view and analyze registrations and judge participants for SLTS-2025.', 
  'https://github.com/Ashrockzzz2003/slts-2024', 
  '{"Ashrockzzz2003"}', 
  '{"Firebase", "Next", "TailwindCSS", "Javascript", "Python"}',
  true),
(
  gen_random_uuid(),
  'Vault 007 v2.0', 
  'Flutter Mobile app to manage and remember passwords.', 
  'https://github.com/Ashrockzzz2003/Vault_007', 
  '{"Ashrockzzz2003"}', 
  '{"Flutter", "Dart", "MUI"}',
  true),
(
  gen_random_uuid(),
  'ANSAN v4.0', 
  'Mobile app to detect glaucoma early, powered by Firebase.', 
  'https://github.com/Ashrockzzz2003/ansan_v3', 
  '{"Ashrockzzz2003"}', 
  '{"Flutter", "Firebase", "Dart"}',
  true),
(
  gen_random_uuid(),
  'Anokha 2025 Event Proposals Management App',
  'A platform for submitting, reviewing, and managing event proposals for Anokha 2025.',
  'https://github.com/SudharsanSaravanan/event-proposal-app', 
  '{"Ashrockzzz2003"}',
  '{"Firebase", "Next", "JavaScript", "TailwindCSS"}',
  true),
(
  gen_random_uuid(),
  'File-Sharing App',
  'Seamless encrypted file-sharing tool.',
  'https://github.com/karthik-saiharsh/file-sharing-app', 
  '{"karthik-saiharsh"}',
  '{"Next","TypeScript", "TailwindCSS"}',
  true),
(
  gen_random_uuid(),
  'Hangman-Game',
  'Simple Hangman-Game made with JavaScript and Django',
  'https://github.com/BIJJUDAMA/Hangman-Game', 
  '{"BIJJUDAMA"}',
  '{"HTML","CSS", "Django"}',
  true),
(
  gen_random_uuid(),
  'Project Rainstorm : Peer',
  'Peer application for a bit-torrent clone written in Golang implementing peer-to-peer file sharing platform over QUIC connections.',
  'https://github.com/aadit-n3rdy/rainstorm_peer', 
  '{"aadit-n3rdy"}',
  '{"Go","Docker"}',
  true),
(
  gen_random_uuid(),
  'Project Rainstorm : Tracker',
  'Tracker application for a bit-torrent clone written in Golang implementing peer-to-peer file sharing platform over QUIC connections.',
  'https://github.com/aadit-n3rdy/rainstorm_tracker', 
  '{"aadit-n3rdy"}',
  '{"Go","Docker"}',
  true),
(
  gen_random_uuid(),
  'Project Rainstorm : Common',
  'Common utilities for a bit-torrent clone written in Golang implementing peer-to-peer file sharing platform over QUIC connections.',
  'https://github.com/aadit-n3rdy/rainstorm_common', 
  '{"aadit-n3rdy"}',
  '{"Go","Docker"}',
  true),
(
  gen_random_uuid(),
  'Dwarka Run: A Java Game Engine',
  'A game engine with an Entity Component System, written in Java that uses OpenGL for 2D rendering.',
  'https://github.com/aadit-n3rdy/DwarkaRun', 
  '{"aadit-n3rdy"}',
  '{"Java","OpenGL"}',
  true),
(
  gen_random_uuid(),
  'Bay-6: Interpreter',
  'A BASIC-like interpreter written in Haskell',
  'https://github.com/aadit-n3rdy/bay6', 
  '{"aadit-n3rdy"}',
  '{"Haskell"}',
  true),
(
  gen_random_uuid(),
  'Smart Asteroids',
  'Asteroids, but if they evolved over time. A space to implement and test our evolutionary algorithms, in a fun intuitive way.',
  'https://github.com/aadit-n3rdy/smart_asteroids', 
  '{"aadit-n3rdy"}',
  '{"Python", "Numpy", "Pygame"}',
  true),
(
  gen_random_uuid(),
  'Phy6: A Physics Simulator',
  'An electrostatics simulation with the scope of expansion into other kinf of forces, better visualization techniques and improved logging.',
  'https://github.com/aadit-n3rdy/phy6', 
  '{"aadit-n3rdy"}',
  '{"C++", "SDL2"}',
  true),
(
  gen_random_uuid(),
  'Gochaat: A Chat App in Go',
  'A very minimalistic repo as of now, primarily aiming to let people explore Golang. Scope of expansion into group chats, auth and verifying certificates with a "no-external services" policy.',
  'https://github.com/aadit-n3rdy/gochaat', 
  '{"aadit-n3rdy"}',
  '{"Go"}',
  true),
(
  gen_random_uuid(),
  'Whodis: Keys, Values and Concurrency',
  'The cliched redis-clone of this edition with signification simplifications. It aims to let people explore Java with the scope for writing client libraries, docs, defining APIs, bloom-filters, etc.',
  'https://github.com/aadit-n3rdy/whodis-server', 
  '{"aadit-n3rdy"}',
  '{"Java"}',
  true),
(
  gen_random_uuid(),
  'Load-Pulse: Load Testing Tool',
  'A CLI-based load testing tool that uses Raft. Follows microservice architecture with each service running in a contianer. Currently it only supports load-testing for HTTP but can be extended to support additional protocols and scaled using k8s instead of docker-compose.',
  'https://github.com/Naganathan05/Load-Pulse', 
  '{"Naganathan05"}',
  '{"Go", "Docker", "Redis", "RabbitMQ", "Cobra"}',
  true),
(
  gen_random_uuid(),
  'NodeGainsDB: Ligthweight In-Memory GraphDB',
  'A jacked Python graph DB with nodes and edges. Lift data with GymQL, spot connections, and flex your gains. Indexed for speed, stored in JSON, and terminal-run. Build your data muscles!',
  'https://github.com/Astrasv/NodeGainsDB',
  '{"Astrasv"}',
  '{"Python"}',
  true),
(
  gen_random_uuid(),
  'Rubiks Cube Solver',
  'This project solves Rubik Cubes from a given state to goal state using BFS, IDDFS and IDA* search algorithms.',
  'https://github.com/Astrasv/CubeSolver',
  '{"Astrasv"}',
  '{"Python"}',
  true),
(
  gen_random_uuid(),
  'Notivos-AI',
  'A simple desktop note-taking application built using Electron.js. The application supports basic CRUD operations, sorting and searching, text-to-speech and a context-aware chatbot via Gemini',
  'https://github.com/adithya-menon-r/Notivos-AI',
  '{"adithya-menon-r"}',
  '{"HTML", "CSS", "JavaScript", "Electron", "Gemini"}',
  true),
(
  gen_random_uuid(),
  'Gradia',
  'An AI-powered platform offering automated answer grading, coding test evaluation, and performance analytics. It uses RAG to ground grading in course materials and return context-aware feedback with citations.',
  'https://github.com/tokenomists/Gradia',
  '{"adithya-menon-r"}',
  '{"Next", "TailwindCSS", "Flask", "Node", "Express", "MongoDB", "GCP"}',
  true),
(
  gen_random_uuid(),
  'Hex: The App Launcher',
  'A powerful global-search to boost your productivity on Windows and Linxu desktops. Search the web, control system settings, perform calculations and lots more.',
  'https://github.com/karthik-saiharsh/hex-launcher',
  '{"karthik-saiharsh", "Leela0o5"}',
  '{"HTML", "CSS", "JavaScript", "Electron"}',
  true),
(
  gen_random_uuid(),
  'CreDebt',
  'Maintain credits and debts between friends with CredDebt the Kotlin app powered with Jetpack Compose',
  'https://github.com/airyha/CreDebt',
  '{"airyha"}',
  '{"Kotlin", "Android", "SQlite", "Jetpack Compose"}',
  true),
(
  gen_random_uuid(),
  'Study Buddy',
  'An app for students to organize common study-spaces and ease details sharing.',
  'https://github.com/airyha/StudyBuddy',
  '{"airyha"}',
  '{"Kotlin", "Android", "SQlite", "Jetpack Compose"}',
  true),
(
  gen_random_uuid(),
  'Vimposter (aka Typotamer)',
  'A vim-like text-editor built with Rust',
  'https://github.com/airyha/Typotamer',
  '{"airyha"}',
  '{"Rust"}',
  true),
(
  gen_random_uuid(),
  'SkillUp',
  'An AI-driven platform that analyzes your resume against target job roles to pinpoint skill gaps and provides personalized learning resources, including curated courses, tutorials, and project ideas to boost your career readiness.',
  'https://github.com/Nithin0306/skillUp',
  '{"Nithin0306"}',
  '{"React", "FastAPI", "JavaScript", "Python"}',
  true),
(
  gen_random_uuid(),
  'Smart-Todo Application',
  'A project that uses modified heaps to help us complete our tasks effectively. Witness the brand new application developed using Rust and Tauri that can assist you in completing your tasks on time and keep you ahead of others.',
  'https://github.com/Thanus-Kumaar/Smart-Todo-Application',
  '{"Thanus-Kumaar"}',
  '{"Rust", "Tauri", "React", "TailwindCSS", "JavaScript"}',
  true),
(
  gen_random_uuid(),
  'FC-TeamForge Application',
  'A project that uses modified heaps to help us complete our tasks effectively. Witness the brand new application developed using Rust and Tauri that can assist you in completing your tasks on time and keeps you ahead of others.',
  'https://github.com/TharunKumarrA/FC-TeamForge',
  '{"TharunKUmarrA"}',
  '{"Vue","JavaScript"}',
  true),
(
  gen_random_uuid(),
  'FC-TeamForge Server',
  'Backend server that powers team creation, player management and all CRUD operations for FC-TeamForge Application. It is designed to ensure smooth, efficient, and balanced football team formation.',
  'https://github.com/Thanus-Kumaar/FC-TeamForge-server',
  '{"Thanus-Kumaar"}',
  '{"Node","Express", "JavaScript", "MySQL"}',
  true),
(
  gen_random_uuid(),
  'Flowgramming App',
  'A platform-independent graphical authoring tool which allows users to draw nad execute programs using flowcharts.',
  'https://github.com/flowgrammers-org/flowgramming',
  '{"Ashrockzzz2003", "ritwik-m"}',
  '{"HTML", "CSS", "JavaScript"}',
  true),
(
  gen_random_uuid(),
  'Flowgramming Docs',
  'Documentation for Flowgramming, the graphical authoring tool which allows users to draw and execute programs using flowcharts.',
  'https://github.com/flowgrammers-org/flowgramming-manual',
  '{"Ashrockzzz2003", "ritwik-m"}',
  '{"Markdown"}',
  true),
(
  gen_random_uuid(), 
  'PANAM: Money Management App', 
  'Supercharge your investment tracking with this secure, Google Sheets-powered portfolio manager. Visualize growth, analyze performance, and take control of your financial future—all within your private Google ecosystem.', 
  'https://github.com/akshayxml/panam', 
  '{"Ashrockzzz2003", "akshayxml"}', 
  '{"Typescript", "AppScript"}', 
  false),
(
  gen_random_uuid(), 
  'Git-Automater', 
  'A Rust-powered CLI tool that simplifies Git workflows by automating common version control tasks.', 
  'https://github.com/ShyamSundhar1411/git-automater', 
  '{"ShyamSundhar1411"}', 
  '{"Rust"}', 
  false),
(
  gen_random_uuid(), 
  'Structura-Py', 
  'Structura is a CLI tool that automates folder structure generation and dependency management for Python projects.', 
  'https://github.com/ShyamSundhar1411/structura-py', 
  '{"ShyamSundhar1411"}', 
  '{"Python"}', 
  false),
(
  gen_random_uuid(), 
  'Structura-Go', 
  'Structura is a CLI tool for automated folder structure generation and dependency management in Golang projects.',
  'https://github.com/ShyamSundhar1411/structura-go',
  '{"ShyamSundhar1411"}',
  '{"Go", "Cobra"}',
  false),
(
  gen_random_uuid(), 
  'Macchia: Blob-Store', 
  'Distributed blog-storage system implemented by connecting several storage nodes through RabbitMQ channels.',
  'https://github.com/Sheerabth/macchia',
  '{"SakethRamanKS", "Ashrockzzz2003"}',
  '{"Python", "RabbitMQ"}',
  false),
(
  gen_random_uuid(), 
  'GlowBridge', 
  'GlowBridge enables users to scan product barcodes to quickly access detailed nutritional information including the product name and NutriScore, powered by Open Food Facts. The app also features nutritionist booking, allowing users to schedule consulations with experts for personalized dietary guidance.',
  'https://github.com/nasacode1/GlowBridge',
  '{"nasacode1", "ShyamSundhar1411"}',
  '{"Kotlin", "Android", "Firebase"}',
  false),
(
  gen_random_uuid(), 
  'Automatic Train Booking System', 
  'A project using selenium web-driver for automating the ticket booking workflow with payments based on date of journey, train, start and stop codes from the IRCTC website.',
  'https://github.com/aniket2909/train_booking_system',
  '{"aniket2909", "Ashrockzzz2003"}',
  '{"Python", "Selenium"}',
  false),
(
  gen_random_uuid(), 
  'Hand Detector Application', 
  'A neural network from scratch which detects normal stares and hand gestures at a laptop screen.',
  'https://github.com/aniket2909/Hand-Detector',
  '{"aniket2909", "Ashrockzzz2003"}',
  '{"Python", "Matplotlib", "Numpy", "OpenCV"}',
  false);
-- +goose StatementEnd