-- +goose Up

-- +goose StatementBegin
-- All badge related metadata is to be found here.
INSERT INTO badge_info (id, name, description) VALUES
(gen_random_uuid(), 'Hello, Tinkerer', '1 Pull Requests merged'),
(gen_random_uuid(), 'Ninja Contributor', '5 Pull Requests merged'),
(gen_random_uuid(), 'Engineer Overclocked', '10 Pull Requests merged'),
(gen_random_uuid(), 'Doomguy', '20 Pull Requests merged'),
(gen_random_uuid(), 'Sanitizer', 'Get 1 bug reports accepted'),
(gen_random_uuid(), 'Pest Control', 'Get 5 bug reports accepted'),
(gen_random_uuid(), 'Planet Cleanser', 'Get 10 bug reports accepted'),
(gen_random_uuid(), 'Polygot', 'Contribute in 3 different languages'),
(gen_random_uuid(), 'Jack of All Stacks', 'Contribute in 5 different languages'),
(gen_random_uuid(), 'The Scholar', 'Help out 1 person in SoC comms'),
(gen_random_uuid(), 'The Gulliver', 'Help out 3 people in SoC comms'),
(gen_random_uuid(), 'The Oracle', 'Help out 5 people in SoC comms'),
(gen_random_uuid(), 'Lab Assistant', 'Get 1 testing related Pull Requests merged'),
(gen_random_uuid(), 'Quality Assurer', 'Get 5 testing related Pull Requests merged'),
(gen_random_uuid(), 'Full-Coded Alchemist', 'Get 10 testing related Requests merged'),
(gen_random_uuid(), 'High Charity', 'Get 2 feature suggestions accepted'),
(gen_random_uuid(), 'Zeppelin of Mighty Gargantuaness (ZOMG)', 'Get a PR marked for High-Impact'),
(gen_random_uuid(), 'Doc Champ', 'Get 2 documentation Pull Requests merged'),
(gen_random_uuid(), 'Shaman', 'Reach 250 bounty points'),
(gen_random_uuid(), 'Henchman', 'Reach 500 bounty points'),
(gen_random_uuid(), 'Kingpin', 'Reach 750 bounty points'),
(gen_random_uuid(), 'The Godfather', 'Reach 1000 bounty points'),
(gen_random_uuid(), '2 Pincers and Maximum Effort', 'Most Rust issues solved (1st place)'),
(gen_random_uuid(), 'Crabby Coder', 'Most Rust issues solved (2nd place)'),
(gen_random_uuid(), 'Salamander Spirit', 'Most Zig issues solved (1st place)'),
(gen_random_uuid(), 'Salamander Totem', 'Most Zig issues solved (2nd place)'),
(gen_random_uuid(), 'Mamba Mentality', 'Most Python issues solved (1st place)'),
(gen_random_uuid(), 'Basilisk Defanged', 'Most Python issues solved (2nd place)'),
(gen_random_uuid(), 'Apex Gopher', 'Most Go issues solved (1st place)'),
(gen_random_uuid(), 'Primal Gopher', 'Most Go issues solved (2nd place)'),
(gen_random_uuid(), 'Forge Smelter', 'Most JS/TS issues solved (1st place)'),
(gen_random_uuid(), 'Prop Driller', 'Most JS/TS issues solved (2nd place)'),
(gen_random_uuid(), 'Lore Master', 'Make a submission accepted for each weekly challenge'),
(gen_random_uuid(), 'Pirate of Issue-bians', 'Contribute to 10 issues in the same language'),
(gen_random_uuid(), 'Enamoured', 'Got a PR accepted every week for a month');
-- +goose StatementEnd

-- +goose StatementBegin
-- Seed data for maintainers for Season of Code 2025 (S2)
INSERT INTO maintainers (ghUsername, full_name) VALUES
('Ashrockzzz2003', 'Ashwin Narayanan S'),
('karthik-saiharsh', 'Karthik Saiharsh'),
('ShyamSundhar1411', 'Shyam Sundhar'),
('Astrasv', 'Sudharsan Vanamali'),
('akshayxml', 'Akshay M');
-- +goose StatementEnd

-- +goose StatementBegin
-- Seed data for internal and external repos for Season of Code 2025 (S2)
INSERT INTO repository
  (id, name, description, url, maintainers, tags, is_internal) VALUES
(
  gen_random_uuid(),
  'Placement Tracker Web App',
  'Web App for tracking the placement activities of the students of Amrita School of Computing, Coimbatore.',
  'https://github.com/Ashrockzzz2003/placement_tracker_web',
  '{"Ashrockzzz2003"}',
  '{"nextjs", "javascript", "tailwindcss", "chartjs"}',
  true),
(
  gen_random_uuid(),
  'Placement Tracker Server',
  'Backend for the web app for tracking placement activities.',
  'https://github.com/Ashrockzzz2003/placement_tracker_server',
  '{"Ashrockzzz2003"}',
  '{"javascript", "expressjs", "mysql"}',
  true),
(
  gen_random_uuid(),
  'EvOC runner_controller_microservice',
  'Microservice for controlling the execution of Evolutionary Algorithms.',
  'https://github.com/Evolutionary-Algorithms-On-Click/runner_controller_microservice',
  '{"Ashrockzzz2003"}',
  '{"docker", "go", "http", "protobuf", "cookie", "grpc"}',
  true),
(
  gen_random_uuid(),
  'EvOC runner',
  'Component responsible for running the Evolutionary Algorithms.', 
  'https://github.com/Evolutionary-Algorithms-On-Click/runner', 
  '{"Ashrockzzz2003"}', 
  '{"python", "docker", "rabbitmq", "cockroachdb"}',
  true),
(
  gen_random_uuid(),
  'EvOC operations', 
  'Repository for operational aspects and automation.', 
  'https://github.com/Evolutionary-Algorithms-On-Click/operations', 
  '{"Ashrockzzz2003"}', 
  '{"docker", "ansible"}',
  true),
(
  gen_random_uuid(),
  'EvOC user_docs', 
  'Documentation for users of the Evolutionary Algorithms platform.', 
  'https://github.com/Evolutionary-Algorithms-On-Click/user_docs', 
  '{"Ashrockzzz2003"}', 
  '{"markdown", "docs", "vitepress"}',
  true),
(
  gen_random_uuid(),
  'EvOC dev_docs', 
  'Documentation for developers contributing to the Evolutionary Algorithms platform.', 
  'https://github.com/Evolutionary-Algorithms-On-Click/dev_docs', 
  '{"Ashrockzzz2003"}', 
  '{"markdown", "docs", "vitepress"}', 
  true),
(
  gen_random_uuid(),
  'EvOC frontend', 
  'Frontend for the Evolutionary Algorithms platform.', 
  'https://github.com/Evolutionary-Algorithms-On-Click/evolve_frontend', 
  '{"Ashrockzzz2003"}', 
  '{"nextjs", "cookies", "gemini", "tailwindcss", "vercel"}',
  true),
(
  gen_random_uuid(),
  'EvOC auth_microservice', 
  'Microservice for handling authentication for the platform.', 
  'https://github.com/Evolutionary-Algorithms-On-Click/auth_microservice', 
  '{"Ashrockzzz2003"}', 
  '{"docker", "go", "http", "protobuf", "cookie", "grpc"}',
  true),
(
  gen_random_uuid(),
  'Quick Start Express', 
  'A simple CLI tool to generate Express servers from multiple available templates.', 
  'https://github.com/CSE-25/quick_start_express', 
  '{"Ashrockzzz2003"}', 
  '{"javascript", "cli", "vitepress", "markdown"}',
  true),
(
  gen_random_uuid(),
  'Amrita PYQ', 
  'The Amrita PYQ CLI Tool simplifies accessing previous year question papers.', 
  'https://github.com/CSE-25/amrita_pyq', 
  '{"Ashrockzzz2003"}', 
  '{"go", "cli"}',
  true),
(
  gen_random_uuid(),
  'SLTS 2025', 
  'Firebase powered app to view and analyze registrations and judge participants for SLTS-2025.', 
  'https://github.com/Ashrockzzz2003/slts-2024', 
  '{"Ashrockzzz2003"}', 
  '{"firebase", "nextjs", "tailwindcss", "javascript", "python"}',
  true),
(
  gen_random_uuid(),
  'Vault 007 v2.0', 
  'Flutter Mobile app to manage and remember passwords.', 
  'https://github.com/Ashrockzzz2003/Vault_007', 
  '{"Ashrockzzz2003"}', 
  '{"flutter", "dart", "material"}',
  true),
(
  gen_random_uuid(),
  'ANSAN v4.0', 
  'Mobile app to detect glaucoma early, powered by Firebase.', 
  'https://github.com/Ashrockzzz2003/ansan_v3', 
  '{"Ashrockzzz2003"}', 
  '{"flutter", "firebase", "dart"}',
  true),
(
  gen_random_uuid(),
  'Anokha 2025 Event Proposals Management App',
  'A platform for submitting, reviewing, and managing event proposals for Anokha 2025.',
  'https://github.com/SudharsanSaravanan/event-proposal-app', 
  '{"Ashrockzzz2003"}',
  '{"firebase", "nextjs", "javascript", "tailwindcss"}',
  true),
(
  gen_random_uuid(),
  'NodeGainsDB: Ligthweight In-Memory GraphDB',
  'A jacked Python graph DB with nodes and edges. Lift data with GymQL, spot connections, and flex your gains. Indexed for speed, stored in JSON, and terminal-run. Build your data muscles!',
  'https://github.com/Astrasv/NodeGainsDB',
  '{"Astrasv"}',
  '{"python"}',
  true),
(
  gen_random_uuid(),
  'File-Sharing-App',
  'A web application for sharing files.', 
  'https://github.com/karthik-saiharsh/file-sharing-app',
  '{"karthik-saiharsh"}',
  '{"nextjs", "typescript"}',
  true),
(
  gen_random_uuid(),
  'Rubiks Cube Solver (3x3 and 2x2)',
  'This project uses breadth-first search (BFS), iterative deepening depth-first search (IDDFS), and iterative deepening A* (IDA*) algorithms to efficiently solve the Rubiks Cube from any starting state to the solved configuration',
  'https://github.com/Astrasv/CubeSolver',
  '{"Astrasv"}',
  '{"python","reactjs", "javascript"}',
  true),
(
  gen_random_uuid(), 
  'PANAM (Money Management related App)', 
  'Supercharge your investment tracking with this secure, Google Sheets-powered portfolio manager. Visualize growth, analyze performance, and take control of your financial future—all within your private Google ecosystem.', 
  'https://github.com/akshayxml/panam', 
  '{"Ashrockzzz2003", "akshayxml"}', 
  '{"google-sheets", "typescript", "google-appscript"}', 
  false),
(
  gen_random_uuid(), 
  'Git-automater', 
  'A Rust-powered CLI tool that simplifies Git workflows by automating common version control tasks.', 
  'https://github.com/ShyamSundhar1411/git-automater', 
  '{"ShyamSundhar1411"}', 
  '{"rust", "cli"}', 
  false),
(
  gen_random_uuid(), 
  'Structura-py', 
  'Structura is a CLI tool that automates folder structure generation and dependency management for Python projects.', 
  'https://github.com/ShyamSundhar1411/structura-py', 
  '{"ShyamSundhar1411"}', 
  '{"python", "cli"}', 
  false),
(
  gen_random_uuid(), 
  'Structura-Go', 
  'Structura is a CLI tool for automated folder structure generation and dependency management in Golang projects.',
  'https://github.com/ShyamSundhar1411/structura-go',
  '{"ShyamSundhar1411"}',
  '{"go", "cli"}',
  false);
-- +goose StatementEnd

